### ISSUE TITLE
What is purpose of StringifyHandler?

### ISSUE THREAD

**Issue by pawaclawczyk** [ClearcodeHQ/SimpleBusElkBundle#3]
I don't understand purpose of `StringifyHandler`.
- Name of class is not saying what are going to stringify, so user can think that it stringifies everythink.
- It does not even stringify, it returns `\DateTime` instance.
- What for do we need special handler for `Carbon` when it extends `\DateTime`?

**Comment by krymen** [comment]
It introduces a dependency with `carbon` which we should avoid. I suggest to remove it from the repo and keep it in particular project itself.

**Comment by krymen** [comment]
Done in #8
