### ISSUE TITLE
Propose a better name

### ISSUE THREAD

**Issue by krymen** [ClearcodeHQ/SimpleBusElkBundle#6]

**Comment by krymen** [comment]
The main responsibility of this library is to integrate monolog with ELK. Serialization (via JMS Serializer) and integration with command bus (at the moment only with SimpleBus) are only additional features. 

After discussion with @pawaclawczyk, the proposition is to rename it to `elk-monolog-bridge`. 

@redarmyman, @tabok, @JacekJagiello, @Lucaszz What's your opinion?

**Comment by lzakrzewski** [comment]
This is symfony bundle so name should be: `elk-monolog-bundle`

**Comment by krymen** [comment]
Bundle is only part of the codebase. Just like in "command-bus-console".

**Comment by jacekjagiello** [comment]
`elk-monolog-integration`? Or just `elk-monolog`.

**Comment by krymen** [comment]
`elk-monolog` looks like a good option. In that case bundle class would be named `ElkMonologBundle`, not `ElkMonologBridgeBundle`.

**Comment by krymen** [comment]
After long discussion with @Lucaszz and @pawaclawczyk we decided to stay with current name as the new name does not introduce any clarification at all ;)
